general:
  artifacts:
    - "jscs.md" # javascript code style

dependencies:
  override:
    - nvm exec $(node -e 'console.log(require("./package.json").engines.node);') npm install
  cache_directories:
      - "~/.npm"
test:
  override:
    - nvm exec $(node -e 'console.log(require("./package.json").engines.node);') npm run build-doc
