name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: help wanted
        if: github.event.label.name == 'pull request wanted'
        uses: actions-cool/issues-helper@v1.8
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome to send us a Pull Request for it. We appreciate your effort in advance and looking forward to your contribution!
