# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
        - Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@zakwarlord7 
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
zakwarlord7
/
ZACHRY-T-WOOD
Public
forked from airbnb/javascript
Code
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
ZACHRY-T-WOOD
/
.github
/
workflows
/
main.yml
in
master
 

Spaces

2

No wrap
1
# This is a basic workflow to help you get started with Actions
2
​
3
name: CI
4
​
5
# Controls when the workflow will run
6
on:
7
  # Triggers the workflow on push or pull request events but only for the "master" branch
8
  push:
9
    branches: [ "master" ]
10
  pull_request:
11
    branches: [ "master" ]
12
​
13
  # Allows you to run this workflow manually from the Actions tab
14
  workflow_dispatch:
15
​
16
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
17
jobs:
18
  # This workflow contains a single job called "build"
19
  build:
20
    # The type of runner that the job will run on
21
    runs-on: ubuntu-latest
22
​
23
    # Steps represent a sequence of tasks that will be executed as part of the job
24
    steps:
25
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
26
      - uses: actions/checkout@v3
27
​
28
      # Runs a single command using the runners shell
29
      - name: Run a one-line script
30
        run: echo Hello, world!
31
​
32
      # Runs a set of commands using the runners shell
33
      - name: Run a multi-line script
34
        run: |
35
          echo Add other actions to build,
36
          echo test, and deploy your project.
37
​
Use Control + Space to trigger autocomplete in most situations.
 / Upload a Build Artifact
Upload a Build Artifact
By actions 
 v3.1.0
 1.8k
Upload a build artifact that can be used by subsequent workflow steps

View full Marketplace listing
Installation
Copy and paste the following snippet into your .yml file.

Version: v3.1.0 
- name: Upload a Build Artifact
  uses: actions/upload-artifact@v3.1.0
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
          echo Add other actions to build,
          echo test, and deploy your project.
